markdown: kramdown
highlighter: pygments
permalink: /:categories/:title
timezone: India/Kolkata
categories: [blog,notes,writing]
# baseurl: "http://pradeepsingh.xyz/"

name: Pradeep Singh
author: Pradeep Singh
title: 'Pradeep Singh'
email: contact@pradeepsingh.xyz
twitter: '@nomadic_enggr'
description: 'Pradeep Singh is an Young Entreprenuer, Writer based out of Mumbai and presently working in a Research Institute.'
